heat_template_version: 2013-05-23

description: This template deploys a router, a private network and a single basic server with a security group.

parameters:

  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: ext-net-doctorado

  private_network_cidr:
    type: string
    label: Private network CIDR
    description: Private Network CIDR
    default: 192.168.200.0/24

  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: Ubuntu-Server-14.04-CECAD-r20141201

  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.small

 
resources:

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_network }

  private_network:
    type: OS::Neutron::Net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_network }
      cidr: {get_param: private_network_cidr}
      dns_nameservers:
        - 8.8.8.8

  router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet: { get_resource: private_subnet }

  web_server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: web_server_security_group
      rules:
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22

  my_keypair:
    type: OS::Nova::KeyPair
    properties:
        name: cloudapps
        save_private_key: True

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }

  server_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: private_network }
      security_groups:
        - { get_resource: web_server_security_group }

  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_resource: my_keypair }
      availability_zone: hpc-test
      networks:
        - port: { get_resource: server_port }
      user_data: |
        #!/bin/sh
        sudo apt-get -y update && sudo apt-get -y install apache2 && sudo service apache2 restart
      user_data_format: RAW

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: server_port }
  

outputs:
    my_instance_name:
      description: Name of the instance
      value: { get_attr: [my_instance, name] }
    my_instance_ip:
      description: IP address of the instance
      value: { get_attr: [my_instance, first_address] }
    my_instance_floating_ip:
      description: The IP address of the deployed instance
      value: { get_attr: [floating_ip, floating_ip_address] }
      

