heat_template_version: 2013-05-23

description: This template deploys a router with a port in the public interface

parameters:

  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: ext-net-doctorado
 
resources:

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_network }